#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TwoStudy.Resource", IsApplication=true)]

namespace TwoStudy
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int cardview_dark_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_light_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_shadow_end_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int cardview_shadow_start_color = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int color_1 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int color_2 = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int interfaceAdditional = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int interfacePrime = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int text2 = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int textMain = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int xam_blue = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int xam_dark_blue = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int xam_gray = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int xam_green = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int xam_light_gray = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int xam_medium_blue = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int xam_purple = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060003
			public const int MarginSchedule = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int cardview_compat_inset_shadow = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_default_elevation = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_default_radius = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int mycircle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int rect_blue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int rect_orange = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int rect_red = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int shape = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int shape2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int xamarin = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int xamarin_white = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000e
			public const int action_0 = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int action_1 = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int action_2 = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int action_edit = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int action_save = 2131361810;
			
			// aapt resource value: 0x7f0a0001
			public const int layoutChangelog = 2131361793;
			
			// aapt resource value: 0x7f0a0003
			public const int llMonday = 2131361795;
			
			// aapt resource value: 0x7f0a0009
			public const int llMonday0 = 2131361801;
			
			// aapt resource value: 0x7f0a0005
			public const int llMondayLessons = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int llMondayTime0 = 2131361798;
			
			// aapt resource value: 0x7f0a0000
			public const int myButton = 2131361792;
			
			// aapt resource value: 0x7f0a0004
			public const int txtDayMonday = 2131361796;
			
			// aapt resource value: 0x7f0a000c
			public const int txtMonday0AddInfo = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int txtMonday0AddInfo2 = 2131361805;
			
			// aapt resource value: 0x7f0a000a
			public const int txtMonday0Subject = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int txtMonday0Teacher = 2131361803;
			
			// aapt resource value: 0x7f0a0002
			public const int txtScheduleInfo = 2131361794;
			
			// aapt resource value: 0x7f0a0007
			public const int txtTimeMonday1 = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int txtTimeMonday2 = 2131361800;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Changelog = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Schedule = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int MenuButton = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int MenuToolbox = 2131296257;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_action_content_save = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_action_edit = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_notification = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Icon = 2130903043;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080003
			public const int app_name = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int hello = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int str0_0_2_alpha2 = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int str0_0_2_alpha3 = 2131230721;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Base_CardView = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int CardView = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int CardView_Dark = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int CardView_Light = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
