#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TwoStudy.Resource", IsApplication=true)]

namespace TwoStudy
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060007
			public const int color_1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int color_2 = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int xam_blue = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int xam_dark_blue = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int xam_gray = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int xam_green = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int xam_light_gray = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int xam_medium_blue = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int xam_purple = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int mycircle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int rect_blue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int rect_orange = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int rect_red = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int shape = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int shape2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int xamarin = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int xamarin_white = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int action_0 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int action_1 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int action_2 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int action_edit = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int action_save = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int layoutChangelog = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int myButton = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Changelog = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int MenuButton = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MenuToolbox = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_action_content_save = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_action_edit = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_notification = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Icon = 2130903043;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int str0_0_1_alpha1 = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
